### ISSUE TITLE
does it really obfuscate the code?

### ISSUE THREAD

**Issue by giuliozelante** [flavior121/uglify-php#1]
From what I saw, what it does is just remove comments and whitespaces, not even every kind of comment

**Comment by isflavior** [comment]
It can replace variables and remove T_COMMENT and T_DOC_COMMENT based on PHP Parser Tokens.

**Comment by giuliozelante** [comment]
### this was the result using no options:

# **source**
`<?php get_header(); ?>

	<main role="main">
		
		<section>

			
			<article id="post-404">

				<h1><?php _e( 'Page not found', 'html5blank' ); ?></h1>
				<h2>
					<a href="<?php echo home_url(); ?>"><?php _e( 'Return home?', 'html5blank' ); ?></a>
				</h2>

			</article>
			

		</section>
		
	</main>

<?php //get_sidebar(); ?>

<?php get_footer(); ?>`

# **output**
`<?php get_header();?>

	<main role="main">
		
		<section>

			
			<article id="post-404">

				<h1><?php _e('Page not found','html5blank');?></h1>
				<h2>
					<a href="<?php echo home_url();?>"><?php _e('Return home?','html5blank');?></a>
				</h2>

			</article>
			

		</section>
		
	</main>

<?php ?>

<?php get_footer();?>`

**Comment by isflavior** [comment]
From what I'm seeing here the uglify-php did his job. 
In your case the output code is very similar from the input code because it don't have variables but it removed the whitespaces from the PHP script (code inside PHP tags).

This package will not change any function name or create "junk code" for performance reasons.
This is meant to be a simple solution for minify and create some obfuscation.

Btw, it will not change any HTML code.

**Comment by giuliozelante** [comment]
Yes confirmed it works, what about the uglifying though?

**Comment by isflavior** [comment]
What do you mean by "uglifying though"?
Are you suggesting that it should minify the HTML too?

**Comment by giuliozelante** [comment]
yes "uglifying" means that it should also put the code on one line

**Comment by isflavior** [comment]
It will work in a fully PHP file (with no HTML).
Anyway i will add a parameter to minify HTML too.
